name: Lint source code
          
on: push

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Update source code
        run: psf/black@stable
        with:
          options: ""

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Enrique Fernandez-Blanco
          author_email: ennanco@gmail.com
          message: '[Automatic] Formatting of the files using Black'
          add: '.'
