name: Format source code

on:
  push:

permissions:
  contents: write

jobs:
  format:
    name: Lint and format with Ruff
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: python -m pip install ruff

      - name: Lint source code
        run: ruff check . --fix

      - name: Format source code
        run: ruff format .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "style: lint and format code with ruff"
          add: "."
